networks:
  selenium-network:
    driver: bridge

services:
  chromium:
    image: selenium/standalone-chromium:latest
    container_name: chromium
    ports:
      - "4444:4444"  # Expose the WebDriver API
    volumes:
      - /dev/shm:/dev/shm  # To avoid "no space left on device" errors with Firefox
    networks:
      - selenium-network
    restart: always

  app:
    build: .
    container_name: app
    environment:
      - WEBDRIVER_URL=http://chromium:4444/wd/hub  # Connect to the standalone Firefox WebDriver
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    depends_on:
      - chromium
    volumes:
      - ./data:/app/data
    networks:
      - selenium-network
    restart: always