networks:
  selenium-network:
    driver: bridge

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    ports:
      - "4444:4444"  # Expose the WebDriver API
    volumes:
      - /dev/shm:/dev/shm  # To avoid "no space left on device" errors with Chrome
    networks:
      - selenium-network
    restart: always

  app:
    build: .
    container_name: app
    environment:
      - WEBDRIVER_URL=http://chrome:4444/wd/hub  # Connect to the standalone Chrome WebDriver
      - PYTHONUNBUFFERED=1
    depends_on:
      - chrome
    volumes:
      - ./data:/app/data
    networks:
      - selenium-network
    restart: always