services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    restart: always

  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    environment:
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    restart: always


  app:
    build: .
    container_name: app
    environment:
      - HUB_HOST=selenium-hub
    depends_on:
      - selenium-hub
      - chrome
    links:
      - selenium-hub
    volumes:
      - ./data:/app/data  # Mount the /data folder
    restart: always  # Auto-restart if the container crashes