networks:
  selenium-network:
    driver: bridge

services:
  firefox:
    image: selenium/standalone-firefox:latest
    container_name: firefox
    ports:
      - "4444:4444"  # Expose the WebDriver API
    volumes:
      - /dev/shm:/dev/shm  # To avoid "no space left on device" errors with Firefox
    networks:
      - selenium-network
    restart: always

  app:
    build: .
    container_name: app
    environment:
      - WEBDRIVER_URL=http://firefox:4444/wd/hub  # Connect to the standalone Firefox WebDriver
      - PYTHONUNBUFFERED=1
    depends_on:
      - firefox
    volumes:
      - ./data:/app/data
    networks:
      - selenium-network
    restart: always